backend:
  name: git-gateway
  branch: main # Changez en 'master' si votre branche principale s'appelle master

media_folder: "images"
public_folder: "/images"

collections:
  - name: "contenu_site"
    label: "Contenu du site"
    files:
      - label: "Mes Services"
        name: "services"
        file: "data/menu.json"
        fields:
          # Le "name" ici DOIT être "plats" pour correspondre à votre code HTML
          - label: "Liste des Services"
            name: "plats"
            widget: "list"
            fields:
              - {label: "Nom du service", name: "nom", widget: "string"}
              - {label: "Prix et détails", name: "prix", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              
      - label: "Mes Créations "
        name: "creations"
        file: "data/creations.json"
        fields:
          - label: "Galerie"
            name: "galerie"
            widget: "list"
            fields:
              - {label: "Nom du plat", name: "titre", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}

              - label: "Catégorie (Onglet)"
                name: "categorie"
                widget: "select"
                options: ["signatures", "entrees", "apero", "desserts"]
