backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "Menu du Restaurant"
    folder: "data"
    extension: "json"
    create: false
    files:
      - file: "data/menu.json"
        label: "Les Plats"
        name: "plats"
        fields:
          - label: "Plats"
            name: "plats"
            widget: "list"
            fields:
              - {label: "Nom du plat", name: "nom", widget: "string"}
              - {label: "Prix", name: "prix", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Photo", name: "image", widget: "image"}

  - name: "galerie"
    label: "Galerie d'images"
    folder: "data/galerie"
    extension: "json"
    create: true
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Légende", name: "legende", widget: "string", required: false}
      - {label: "Texte alternatif", name: "alt", widget: "string", required: false}
